CRITICAL - 2025-04-09 09:49:25 --> ErrorException: Undefined variable $totalTime
[Method: GET, Route: /]
in SYSTEMPATH\Debug\Toolbar\Views\toolbar.tpl.php on line 46.
 1 SYSTEMPATH\Debug\Toolbar\Views\toolbar.tpl.php(46): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $totalTime', 'C:\\xampp\\htdocs\\Tesina\\system\\Debug\\Toolbar\\Views\\toolbar.tpl.php', 46)
 2 SYSTEMPATH\Debug\Toolbar.php(534): include('C:\\xampp\\htdocs\\Tesina\\system\\Debug\\Toolbar\\Views\\toolbar.tpl.php')
 3 SYSTEMPATH\Debug\Toolbar.php(497): CodeIgniter\Debug\Toolbar->format([...], 'html')
 4 APPPATH\Config\Events.php(47): CodeIgniter\Debug\Toolbar->respond()
 5 SYSTEMPATH\Events\Events.php(155): CodeIgniter\Events\Events::Config\{closure}()
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\Events\Events::trigger('pre_system')
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-09 18:05:12 --> mysqli_sql_exception: Unknown column 'admin_id' in 'field list' in C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `in...', 0)
#1 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `in...')
#2 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `in...')
#3 C:\xampp\htdocs\Tesina\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `in...', Array, false)
#4 C:\xampp\htdocs\Tesina\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tesina\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tesina\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tesina\app\Models\InvitacionModel.php(22): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Tesina\app\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.c...', NULL, '2')
#9 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
#10 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#11 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Tesina\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Tesina\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Tesina\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-04-09 18:05:12 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'admin_id' in 'field list'
[Method: POST, Route: admin/enviarInvitacion]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `admin_id`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (:email:, :token:, :admin_id:, :rol:, :expires_at:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:05:12 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'admin_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `admin_id`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'pPUVU68BpG4c1zOLEcRfmb9xOF3bjji2\', NULL, \'2\', \'2025-04-10 18:05:12\', \'2025-04-09 18:05:12\', \'2025-04-09 18:05:12\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `admin_id`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'pPUVU68BpG4c1zOLEcRfmb9xOF3bjji2\', NULL, \'2\', \'2025-04-10 18:05:12\', \'2025-04-09 18:05:12\', \'2025-04-09 18:05:12\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `admin_id`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (:email:, :token:, :admin_id:, :rol:, :expires_at:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:05:12 --> [Caused by] mysqli_sql_exception: Unknown column 'admin_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `invitaciones` (`email`, `token`, `admin_id`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'pPUVU68BpG4c1zOLEcRfmb9xOF3bjji2\', NULL, \'2\', \'2025-04-10 18:05:12\', \'2025-04-09 18:05:12\', \'2025-04-09 18:05:12\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `admin_id`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'pPUVU68BpG4c1zOLEcRfmb9xOF3bjji2\', NULL, \'2\', \'2025-04-10 18:05:12\', \'2025-04-09 18:05:12\', \'2025-04-09 18:05:12\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `admin_id`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'pPUVU68BpG4c1zOLEcRfmb9xOF3bjji2\', NULL, \'2\', \'2025-04-10 18:05:12\', \'2025-04-09 18:05:12\', \'2025-04-09 18:05:12\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `admin_id`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (:email:, :token:, :admin_id:, :rol:, :expires_at:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-09 18:09:40 --> mysqli_sql_exception: Unknown column 'rol' in 'field list' in C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `in...', 0)
#1 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `in...')
#2 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `in...')
#3 C:\xampp\htdocs\Tesina\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `in...', Array, false)
#4 C:\xampp\htdocs\Tesina\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tesina\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tesina\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tesina\app\Models\InvitacionModel.php(22): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Tesina\app\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.c...', NULL, '2')
#9 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
#10 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#11 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Tesina\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Tesina\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Tesina\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-04-09 18:09:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'rol' in 'field list'
[Method: POST, Route: admin/enviarInvitacion]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (:email:, :token:, :id_usuario:, :rol:, :expires_at:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:09:40 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'rol' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'ZySCgjYu98ZfQRAkNqiU69tUVx2gaZle\', NULL, \'2\', \'2025-04-10 18:09:40\', \'2025-04-09 18:09:40\', \'2025-04-09 18:09:40\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'ZySCgjYu98ZfQRAkNqiU69tUVx2gaZle\', NULL, \'2\', \'2025-04-10 18:09:40\', \'2025-04-09 18:09:40\', \'2025-04-09 18:09:40\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (:email:, :token:, :id_usuario:, :rol:, :expires_at:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:09:40 --> [Caused by] mysqli_sql_exception: Unknown column 'rol' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'ZySCgjYu98ZfQRAkNqiU69tUVx2gaZle\', NULL, \'2\', \'2025-04-10 18:09:40\', \'2025-04-09 18:09:40\', \'2025-04-09 18:09:40\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'ZySCgjYu98ZfQRAkNqiU69tUVx2gaZle\', NULL, \'2\', \'2025-04-10 18:09:40\', \'2025-04-09 18:09:40\', \'2025-04-09 18:09:40\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'ZySCgjYu98ZfQRAkNqiU69tUVx2gaZle\', NULL, \'2\', \'2025-04-10 18:09:40\', \'2025-04-09 18:09:40\', \'2025-04-09 18:09:40\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (:email:, :token:, :id_usuario:, :rol:, :expires_at:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-09 18:09:45 --> mysqli_sql_exception: Unknown column 'rol' in 'field list' in C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `in...', 0)
#1 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `in...')
#2 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `in...')
#3 C:\xampp\htdocs\Tesina\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `in...', Array, false)
#4 C:\xampp\htdocs\Tesina\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tesina\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tesina\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tesina\app\Models\InvitacionModel.php(22): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Tesina\app\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.c...', NULL, '2')
#9 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
#10 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#11 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Tesina\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Tesina\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Tesina\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-04-09 18:09:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'rol' in 'field list'
[Method: POST, Route: admin/enviarInvitacion]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (:email:, :token:, :id_usuario:, :rol:, :expires_at:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:09:45 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'rol' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'S8aub1MuBlSZacJymteNbnmL3cEtLfTl\', NULL, \'2\', \'2025-04-10 18:09:45\', \'2025-04-09 18:09:45\', \'2025-04-09 18:09:45\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'S8aub1MuBlSZacJymteNbnmL3cEtLfTl\', NULL, \'2\', \'2025-04-10 18:09:45\', \'2025-04-09 18:09:45\', \'2025-04-09 18:09:45\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (:email:, :token:, :id_usuario:, :rol:, :expires_at:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:09:45 --> [Caused by] mysqli_sql_exception: Unknown column 'rol' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'S8aub1MuBlSZacJymteNbnmL3cEtLfTl\', NULL, \'2\', \'2025-04-10 18:09:45\', \'2025-04-09 18:09:45\', \'2025-04-09 18:09:45\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'S8aub1MuBlSZacJymteNbnmL3cEtLfTl\', NULL, \'2\', \'2025-04-10 18:09:45\', \'2025-04-09 18:09:45\', \'2025-04-09 18:09:45\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'S8aub1MuBlSZacJymteNbnmL3cEtLfTl\', NULL, \'2\', \'2025-04-10 18:09:45\', \'2025-04-09 18:09:45\', \'2025-04-09 18:09:45\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `rol`, `expires_at`, `created_at`, `updated_at`) VALUES (:email:, :token:, :id_usuario:, :rol:, :expires_at:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-09 18:10:51 --> mysqli_sql_exception: Unknown column 'expires_at' in 'field list' in C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `in...', 0)
#1 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `in...')
#2 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `in...')
#3 C:\xampp\htdocs\Tesina\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `in...', Array, false)
#4 C:\xampp\htdocs\Tesina\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tesina\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tesina\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tesina\app\Models\InvitacionModel.php(22): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Tesina\app\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.c...', NULL, '2')
#9 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
#10 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#11 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Tesina\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Tesina\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Tesina\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-04-09 18:10:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'expires_at' in 'field list'
[Method: POST, Route: admin/enviarInvitacion]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `expires_at`, `created_at`, `updated_at`) VALUES (:email:, :token:, :id_usuario:, :id_rol:, :expires_at:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:10:51 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'expires_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'WWvvkYqVvS710ZXDa6eDKZICK65iDdtB\', NULL, \'2\', \'2025-04-10 18:10:51\', \'2025-04-09 18:10:51\', \'2025-04-09 18:10:51\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'WWvvkYqVvS710ZXDa6eDKZICK65iDdtB\', NULL, \'2\', \'2025-04-10 18:10:51\', \'2025-04-09 18:10:51\', \'2025-04-09 18:10:51\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `expires_at`, `created_at`, `updated_at`) VALUES (:email:, :token:, :id_usuario:, :id_rol:, :expires_at:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:10:51 --> [Caused by] mysqli_sql_exception: Unknown column 'expires_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'WWvvkYqVvS710ZXDa6eDKZICK65iDdtB\', NULL, \'2\', \'2025-04-10 18:10:51\', \'2025-04-09 18:10:51\', \'2025-04-09 18:10:51\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'WWvvkYqVvS710ZXDa6eDKZICK65iDdtB\', NULL, \'2\', \'2025-04-10 18:10:51\', \'2025-04-09 18:10:51\', \'2025-04-09 18:10:51\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `expires_at`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'WWvvkYqVvS710ZXDa6eDKZICK65iDdtB\', NULL, \'2\', \'2025-04-10 18:10:51\', \'2025-04-09 18:10:51\', \'2025-04-09 18:10:51\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `expires_at`, `created_at`, `updated_at`) VALUES (:email:, :token:, :id_usuario:, :id_rol:, :expires_at:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-09 18:11:55 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `in...', 0)
#1 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `in...')
#2 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `in...')
#3 C:\xampp\htdocs\Tesina\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `in...', Array, false)
#4 C:\xampp\htdocs\Tesina\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tesina\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tesina\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tesina\app\Models\InvitacionModel.php(22): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Tesina\app\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.c...', NULL, '2')
#9 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
#10 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#11 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Tesina\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Tesina\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Tesina\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-04-09 18:11:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: admin/enviarInvitacion]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `created_at`, `updated_at`) VALUES (:email:, :token:, :id_usuario:, :id_rol:, :fecha_expiracion:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:11:55 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'GoZY0Gj0a4QRNJZ05siiOUTI2vuiNMJb\', NULL, \'2\', \'2025-04-10 18:11:55\', \'2025-04-09 18:11:55\', \'2025-04-09 18:11:55\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'GoZY0Gj0a4QRNJZ05siiOUTI2vuiNMJb\', NULL, \'2\', \'2025-04-10 18:11:55\', \'2025-04-09 18:11:55\', \'2025-04-09 18:11:55\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `created_at`, `updated_at`) VALUES (:email:, :token:, :id_usuario:, :id_rol:, :fecha_expiracion:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:11:55 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'GoZY0Gj0a4QRNJZ05siiOUTI2vuiNMJb\', NULL, \'2\', \'2025-04-10 18:11:55\', \'2025-04-09 18:11:55\', \'2025-04-09 18:11:55\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'GoZY0Gj0a4QRNJZ05siiOUTI2vuiNMJb\', NULL, \'2\', \'2025-04-10 18:11:55\', \'2025-04-09 18:11:55\', \'2025-04-09 18:11:55\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `created_at`, `updated_at`) VALUES (\'lortrns@gmail.com\', \'GoZY0Gj0a4QRNJZ05siiOUTI2vuiNMJb\', NULL, \'2\', \'2025-04-10 18:11:55\', \'2025-04-09 18:11:55\', \'2025-04-09 18:11:55\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `created_at`, `updated_at`) VALUES (:email:, :token:, :id_usuario:, :id_rol:, :fecha_expiracion:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\InvitacionModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-09 18:14:03 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') VALUES ('lortrns@gmail.com', 'D2mY51CVepV6GZNBB8ADo0nwFC9OYhoE', NULL, '2',...' at line 1 in C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `in...', 0)
#1 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `in...')
#2 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `in...')
#3 C:\xampp\htdocs\Tesina\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `in...', Array, false)
#4 C:\xampp\htdocs\Tesina\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tesina\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tesina\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tesina\app\Models\InvitacionModel.php(25): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Tesina\app\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.c...', NULL, '2')
#9 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
#10 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#11 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Tesina\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Tesina\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Tesina\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-04-09 18:14:03 --> CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') VALUES ('lortrns@gmail.com', 'D2mY51CVepV6GZNBB8ADo0nwFC9OYhoE', NULL, '2',...' at line 1
[Method: POST, Route: admin/enviarInvitacion]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (:email:, :token:, :id_usuario:, :id_rol:, :fecha_expiracion:, :estado:, :created_at:, ::)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\InvitacionModel.php(25): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:14:03 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') VALUES ('lortrns@gmail.com', 'D2mY51CVepV6GZNBB8ADo0nwFC9OYhoE', NULL, '2',...' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (\'lortrns@gmail.com\', \'D2mY51CVepV6GZNBB8ADo0nwFC9OYhoE\', NULL, \'2\', \'2025-04-10 18:14:03\', \'pendiente\', \'2025-04-09 18:14:03\', \'2025-04-09 18:14:03\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (\'lortrns@gmail.com\', \'D2mY51CVepV6GZNBB8ADo0nwFC9OYhoE\', NULL, \'2\', \'2025-04-10 18:14:03\', \'pendiente\', \'2025-04-09 18:14:03\', \'2025-04-09 18:14:03\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (:email:, :token:, :id_usuario:, :id_rol:, :fecha_expiracion:, :estado:, :created_at:, ::)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\InvitacionModel.php(25): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:14:03 --> [Caused by] mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') VALUES ('lortrns@gmail.com', 'D2mY51CVepV6GZNBB8ADo0nwFC9OYhoE', NULL, '2',...' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (\'lortrns@gmail.com\', \'D2mY51CVepV6GZNBB8ADo0nwFC9OYhoE\', NULL, \'2\', \'2025-04-10 18:14:03\', \'pendiente\', \'2025-04-09 18:14:03\', \'2025-04-09 18:14:03\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (\'lortrns@gmail.com\', \'D2mY51CVepV6GZNBB8ADo0nwFC9OYhoE\', NULL, \'2\', \'2025-04-10 18:14:03\', \'pendiente\', \'2025-04-09 18:14:03\', \'2025-04-09 18:14:03\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (\'lortrns@gmail.com\', \'D2mY51CVepV6GZNBB8ADo0nwFC9OYhoE\', NULL, \'2\', \'2025-04-10 18:14:03\', \'pendiente\', \'2025-04-09 18:14:03\', \'2025-04-09 18:14:03\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (:email:, :token:, :id_usuario:, :id_rol:, :fecha_expiracion:, :estado:, :created_at:, ::)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\InvitacionModel.php(25): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-09 18:14:38 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') VALUES ('lortrns@gmail.com', '21CAtjyLJpv8pkN7nhIQZxpKttL2MVEd', 0, 2, '202...' at line 1 in C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `in...', 0)
#1 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `in...')
#2 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `in...')
#3 C:\xampp\htdocs\Tesina\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `in...', Array, false)
#4 C:\xampp\htdocs\Tesina\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tesina\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tesina\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tesina\app\Models\InvitacionModel.php(35): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Tesina\app\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.c...', NULL, '2')
#9 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
#10 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#11 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Tesina\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Tesina\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Tesina\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-04-09 18:14:38 --> CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') VALUES ('lortrns@gmail.com', '21CAtjyLJpv8pkN7nhIQZxpKttL2MVEd', 0, 2, '202...' at line 1
[Method: POST, Route: admin/enviarInvitacion]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (:email:, :token:, :id_usuario:, :id_rol:, :fecha_expiracion:, :estado:, :created_at:, ::)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\InvitacionModel.php(35): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:14:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') VALUES ('lortrns@gmail.com', '21CAtjyLJpv8pkN7nhIQZxpKttL2MVEd', 0, 2, '202...' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (\'lortrns@gmail.com\', \'21CAtjyLJpv8pkN7nhIQZxpKttL2MVEd\', 0, 2, \'2025-04-10 18:14:38\', \'pendiente\', \'2025-04-09 18:14:38\', \'2025-04-09 18:14:38\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (\'lortrns@gmail.com\', \'21CAtjyLJpv8pkN7nhIQZxpKttL2MVEd\', 0, 2, \'2025-04-10 18:14:38\', \'pendiente\', \'2025-04-09 18:14:38\', \'2025-04-09 18:14:38\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (:email:, :token:, :id_usuario:, :id_rol:, :fecha_expiracion:, :estado:, :created_at:, ::)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\InvitacionModel.php(35): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:14:38 --> [Caused by] mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') VALUES ('lortrns@gmail.com', '21CAtjyLJpv8pkN7nhIQZxpKttL2MVEd', 0, 2, '202...' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (\'lortrns@gmail.com\', \'21CAtjyLJpv8pkN7nhIQZxpKttL2MVEd\', 0, 2, \'2025-04-10 18:14:38\', \'pendiente\', \'2025-04-09 18:14:38\', \'2025-04-09 18:14:38\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (\'lortrns@gmail.com\', \'21CAtjyLJpv8pkN7nhIQZxpKttL2MVEd\', 0, 2, \'2025-04-10 18:14:38\', \'pendiente\', \'2025-04-09 18:14:38\', \'2025-04-09 18:14:38\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (\'lortrns@gmail.com\', \'21CAtjyLJpv8pkN7nhIQZxpKttL2MVEd\', 0, 2, \'2025-04-10 18:14:38\', \'pendiente\', \'2025-04-09 18:14:38\', \'2025-04-09 18:14:38\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `invitaciones` (`email`, `token`, `id_usuario`, `id_rol`, `fecha_expiracion`, `estado`, `created_at`, ) VALUES (:email:, :token:, :id_usuario:, :id_rol:, :fecha_expiracion:, :estado:, :created_at:, ::)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\InvitacionModel.php(35): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Admin.php(64): App\Models\InvitacionModel->crearInvitacion('lortrns@gmail.com', null, '2')
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin->enviarInvitacion()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-09 18:23:25 --> Intento de inicio de sesión fallido. Email: tomas@gmail.com
ERROR - 2025-04-09 18:23:39 --> Intento de inicio de sesión fallido. Email: brunocameille@alumnos.itr3.edu.ar
ERROR - 2025-04-09 18:24:24 --> ID de usuario inválido: 0
ERROR - 2025-04-09 18:27:53 --> ID de usuario inválido: 0
ERROR - 2025-04-09 18:31:17 --> ID de usuario inválido: 0
ERROR - 2025-04-09 18:31:17 --> Datos de sesión al momento del error:
ERROR - 2025-04-09 18:31:17 --> Array
(
    [__ci_last_regenerate] => 1744234239
    [_ci_previous_url] => http://192.168.0.195/Tesina/public/admin/invitar
    [userData] => Array
        (
            [id_usuario] => 1
            [nombre] => brunito
            [apellido] => barber
            [email] => brunocameille@alumnos.itr3.edu.ar
            [contrasena] => $2y$10$F4xQfULyrVhG1JD8Y21QR.vgn9Fzd257acxjmQqHQ3OYfEqBaAPb6
            [direccion_id] => 0
            [rol] => 0
            [id_rol] => 1
            [created_at] => 2025-04-07 13:37:30
            [updated_at] => 2025-04-07 20:16:03
        )

    [Tipo] => usuario
    [logged_in] => 1
    [rol] => admin
)

ERROR - 2025-04-09 18:33:18 --> Error en enviarInvitacion: Undefined variable $rol
ERROR - 2025-04-09 18:35:28 --> Error en enviarInvitacion: Undefined variable $rol
ERROR - 2025-04-09 18:38:49 --> Error en enviarInvitacion: Undefined variable $rol
ERROR - 2025-04-09 18:47:46 --> mysqli_sql_exception: Table 'login.energia' doesn't exist in C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\Tesina\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Tesina\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tesina\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Tesina\app\Controllers\Energia.php(59): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(933): App\Controllers\Energia->index()
#8 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Energia))
#9 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Tesina\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Tesina\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Tesina\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-04-09 18:47:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'login.energia' doesn't exist
[Method: GET, Route: energia]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `energia`
ORDER BY `id` DESC', [], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Energia.php(59): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Energia->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Energia))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:47:46 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'login.energia' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `energia`
ORDER BY `id` DESC')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `energia`
ORDER BY `id` DESC')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `energia`
ORDER BY `id` DESC', [], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Controllers\Energia.php(59): CodeIgniter\BaseModel->findAll()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Energia->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Energia))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 18:47:46 --> [Caused by] mysqli_sql_exception: Table 'login.energia' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT *
FROM `energia`
ORDER BY `id` DESC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `energia`
ORDER BY `id` DESC')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `energia`
ORDER BY `id` DESC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `energia`
ORDER BY `id` DESC', [], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\Energia.php(59): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Energia->index()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Energia))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-09 19:08:13 --> mysqli_sql_exception: Table 'login.codigos' doesn't exist in C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\Tesina\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\Tesina\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\Tesina\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\Tesina\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tesina\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tesina\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tesina\app\Models\CodigoModel.php(18): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Tesina\app\Controllers\CCorreo.php(37): App\Models\CodigoModel->insertarCodigo(Array)
#9 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(933): App\Controllers\CCorreo->correo()
#10 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CCorreo))
#11 C:\xampp\htdocs\Tesina\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Tesina\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Tesina\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Tesina\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-04-09 19:08:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'login.codigos' doesn't exist
[Method: POST, Route: correo]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `codigos` (`id_usuario`, `codigo`, `expiracion`, `created_at`, `updated_at`) VALUES (:id_usuario:, :codigo:, :expiracion:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\CodigoModel.php(18): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\CCorreo.php(37): App\Models\CodigoModel->insertarCodigo([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CCorreo->correo()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CCorreo))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 19:08:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'login.codigos' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `codigos` (`id_usuario`, `codigo`, `expiracion`, `created_at`, `updated_at`) VALUES (\'1\', 924554, \'2025-04-09 19:23:13\', \'2025-04-09 19:08:13\', \'2025-04-09 19:08:13\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `codigos` (`id_usuario`, `codigo`, `expiracion`, `created_at`, `updated_at`) VALUES (\'1\', 924554, \'2025-04-09 19:23:13\', \'2025-04-09 19:08:13\', \'2025-04-09 19:08:13\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `codigos` (`id_usuario`, `codigo`, `expiracion`, `created_at`, `updated_at`) VALUES (:id_usuario:, :codigo:, :expiracion:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\CodigoModel.php(18): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\CCorreo.php(37): App\Models\CodigoModel->insertarCodigo([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CCorreo->correo()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CCorreo))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-09 19:08:13 --> [Caused by] mysqli_sql_exception: Table 'login.codigos' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `codigos` (`id_usuario`, `codigo`, `expiracion`, `created_at`, `updated_at`) VALUES (\'1\', 924554, \'2025-04-09 19:23:13\', \'2025-04-09 19:08:13\', \'2025-04-09 19:08:13\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `codigos` (`id_usuario`, `codigo`, `expiracion`, `created_at`, `updated_at`) VALUES (\'1\', 924554, \'2025-04-09 19:23:13\', \'2025-04-09 19:08:13\', \'2025-04-09 19:08:13\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `codigos` (`id_usuario`, `codigo`, `expiracion`, `created_at`, `updated_at`) VALUES (\'1\', 924554, \'2025-04-09 19:23:13\', \'2025-04-09 19:08:13\', \'2025-04-09 19:08:13\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `codigos` (`id_usuario`, `codigo`, `expiracion`, `created_at`, `updated_at`) VALUES (:id_usuario:, :codigo:, :expiracion:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\CodigoModel.php(18): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\CCorreo.php(37): App\Models\CodigoModel->insertarCodigo([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CCorreo->correo()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CCorreo))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
